# Generated by Django 5.2.3 on 2025-08-30 16:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='leader_year',
            field=models.DateField(blank=True, default='Nespecificat', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2021, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2025, 12, 31))]),
        ),
    ]
