# Generated by Django 5.2.17 on 2026-08-16 14:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_house_leader_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='leader_year',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2022, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2026, 12, 31))]),
        ),
    ]
