# Generated by Django 5.2.17 on 2026-08-16 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_house_leader_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
