# Generated by Django 5.2.17 on 2026-08-16 17:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_house_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='leader_year',
            field=models.DateField(default='Nespecificat', validators=[django.core.validators.MinValueValidator(datetime.date(2022, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2026, 12, 31))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
